# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=200)),
                ('image_upload', models.ImageField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
